# Generated by Django 3.0.5 on 2020-04-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('subcategory', models.ManyToManyField(related_name='_category_subcategory_+', to='catalog.Category', verbose_name='Подкатегории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('body', models.CharField(max_length=30, null=True, verbose_name='Корпус')),
                ('producer', models.CharField(max_length=30, null=True, verbose_name='Производитель')),
                ('price', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='products/<django.db.models.fields.related.ForeignKey>/', verbose_name='Изображение')),
                ('analog', models.ManyToManyField(blank=True, related_name='_product_analog_+', to='catalog.Product', verbose_name='Аналоги')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
