# Generated by Django 3.0.5 on 2020-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200428_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Для данного товара пока нет описания.', verbose_name='Описание'),
        ),
    ]
